# display
FPS = 60

# colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# screen
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 500, 640
SCREEN_BACKGROUND = BLACK
DISPLAY_WIDTH = SCREEN_WIDTH * 0.9

# word
BASIC_FONT = 'Calibri'
FONT_SIZE = 20
FONT_COLOR = WHITE
WORD_BACKGROUND_COLOR = (200, 10, 10)
WORD_SPEED = [0, 1]

# levels
LEVEL_SPEED = [0, 1]
LEVEL_WORD_COUNT = 5
LEVEL_FREQUENCY = 120
WORD_LENGTH = [2, 5]

# files
WORDS_FILE = "resources/words_dict.txt"
